#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Classify LQ questions into by-topic folders (lq/) + notes/lq-bank.tex."""
from __future__ import annotations

import json
import re
import shutil
import sys
from collections import defaultdict
from pathlib import Path

import pymupdf as fitz

# Reuse MC classifier rules / multi-label logic.
ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
from classify_by_topic import (  # noqa: E402
    CHAPTERS,
    SUBTOPICS,
    classify_multi,
    sort_key,
)

PROCESSED_LQ = ROOT / "processed" / "LQ"
JSON_PATH = PROCESSED_LQ / "lq_questions.json"
OUT_ROOT = ROOT.parent / "notes"

# Manual fixes when OCR/crop bleed misclassifies a known past-paper LQ.
LQ_OVERRIDES: dict[tuple[int | str, int], tuple[str, str]] = {
    (2016, 6): ("Wave Motion", "Wave nature of light"),
}


def png_path(record: dict) -> Path:
    year = record["Year"]
    qn = record["Question"]
    canonical = PROCESSED_LQ / str(year) / f"q{qn}.png"
    if canonical.exists():
        return canonical
    rel = record.get("PNG") or ""
    alt = ROOT / rel
    return alt if alt.exists() else canonical


def dest_name(record: dict) -> str:
    return f"{record['Year']}_q{record['Question']}.png"


def latex_escape(text: str) -> str:
    return (
        text.replace("\\", "\\textbackslash{}")
        .replace("&", "\\&")
        .replace("%", "\\%")
        .replace("#", "\\#")
        .replace("_", "\\_")
    )


def write_lq_bank(chapter: str, subtopic: str, items: list[dict]) -> None:
    notes_dir = OUT_ROOT / chapter / subtopic / "notes"
    notes_dir.mkdir(parents=True, exist_ok=True)
    bank = notes_dir / "lq-bank.tex"
    lines = [
        "% !TEX program = lualatex",
        "% AUTO-GENERATED by scripts/classify_lq_by_topic.py - do not edit by hand.",
        "\\documentclass[11pt,a4paper]{article}",
        "\\input{../../../_notes-shared/preamble.tex}",
        "",
        "\\pagestyle{fancy}",
        "\\fancyhf{}",
        f"\\fancyhead[L]{{\\small {latex_escape(chapter)}}}",
        f"\\fancyhead[R]{{\\small {latex_escape(subtopic)} - LQ}}",
        "\\fancyfoot[C]{\\thepage}",
        "\\renewcommand{\\headrulewidth}{0.4pt}",
        "",
        f"\\title{{\\textbf{{{latex_escape(subtopic)}}}\\\\[0.35em]"
        f"\\large {latex_escape(chapter)} - Long-question bank}}",
        "\\date{}",
        "",
        "\\begin{document}",
        "\\maketitle",
        f"\\noindent All Paper~1B long questions assigned to this topic "
        f"({len(items)} question{'s' if len(items) != 1 else ''}).",
        "\\bigskip",
        "",
    ]
    for record in items:
        year = record["Year"]
        qn = record["Question"]
        png = f"../lq/{dest_name(record)}"
        lines.append(f"\\mcpractice{{{year}}}{{{qn}}}{{{png}}}")
        lines.append("")
    lines.append("\\end{document}")
    lines.append("")
    bank.write_text("\n".join(lines), encoding="utf-8")


def append_pngs(document: fitz.Document, paths: list[Path]) -> None:
    for path in paths:
        image = fitz.open(path)
        try:
            rect = image[0].rect
            page = document.new_page(width=rect.width, height=rect.height)
            page.insert_image(page.rect, filename=str(path))
        finally:
            image.close()


def sync_topic(chapter: str, subtopic: str, items: list[dict]) -> int:
    folder = OUT_ROOT / chapter / subtopic
    lq_dir = folder / "lq"
    lq_dir.mkdir(parents=True, exist_ok=True)
    for path in lq_dir.glob("*_q*.png"):
        path.unlink()

    copied: list[Path] = []
    for record in sorted(items, key=sort_key):
        src = png_path(record)
        if not src.exists():
            print(f"missing png: {src}")
            continue
        dest = lq_dir / dest_name(record)
        shutil.copy2(src, dest)
        copied.append(dest)

    pdf_path = folder / "lq.pdf"
    if copied:
        doc = fitz.open()
        append_pngs(doc, copied)
        doc.save(pdf_path, garbage=4, deflate=True)
        doc.close()
    elif pdf_path.exists():
        pdf_path.unlink()
    legacy = folder / "lq_all.pdf"
    if legacy.exists():
        legacy.unlink()

    write_lq_bank(chapter, subtopic, [r for r in sorted(items, key=sort_key) if png_path(r).exists()])
    return len(copied)


def main() -> None:
    records = json.loads(JSON_PATH.read_text())
    buckets: dict[tuple[str, str], list[dict]] = defaultdict(list)
    classification: list[dict] = []
    n_one = n_two = n_fallback = 0

    for record in records:
        key = (record["Year"], record["Question"])
        if key in LQ_OVERRIDES:
            chapter, subtopic = LQ_OVERRIDES[key]
            topics = [(chapter, subtopic, 999)]
        else:
            topics = classify_multi(record)
        if len(topics) == 1:
            n_one += 1
            if topics[0][2] == 0:
                n_fallback += 1
        else:
            n_two += 1

        topic_rows = []
        for i, (chapter, subtopic, score) in enumerate(topics):
            buckets[(chapter, subtopic)].append(record)
            topic_rows.append(
                {
                    "Chapter": chapter,
                    "Subtopic": subtopic,
                    "score": score,
                    "primary": i == 0,
                }
            )
        primary = topics[0]
        classification.append(
            {
                "Year": record["Year"],
                "Question": record["Question"],
                "Chapter": primary[0],
                "Subtopic": primary[1],
                "score": primary[2],
                "Topics": topic_rows,
                "PNG": record.get("PNG"),
                "Type": "LQ",
            }
        )

    summary: dict[str, dict[str, int]] = {}
    for chapter in CHAPTERS:
        summary[chapter] = {}
        for subtopic in SUBTOPICS[chapter]:
            items = list({(r["Year"], r["Question"]): r for r in buckets.get((chapter, subtopic), [])}.values())
            n = sync_topic(chapter, subtopic, items)
            summary[chapter][subtopic] = n
            if n:
                print(f"{chapter} / {subtopic}: {n}")

    index_path = OUT_ROOT / "lq_classification.json"
    index_path.write_text(json.dumps(classification, indent=2, ensure_ascii=False) + "\n")
    (OUT_ROOT / "lq_summary.json").write_text(json.dumps(summary, indent=2, ensure_ascii=False) + "\n")

    by_id = {(c["Year"], c["Question"]): c for c in classification}
    enriched = []
    for record in records:
        meta = by_id[(record["Year"], record["Question"])]
        enriched.append(
            {
                **{k: v for k, v in record.items() if k not in ("Chapter", "Subtopic", "Topics")},
                "Chapter": meta["Chapter"],
                "Subtopic": meta["Subtopic"],
                "Topics": meta["Topics"],
            }
        )
    JSON_PATH.write_text(json.dumps(enriched, indent=2, ensure_ascii=False) + "\n")

    placements = sum(summary[ch][st] for ch in summary for st in summary[ch])
    print(f"Updated {JSON_PATH}")
    print(f"Wrote {index_path}")
    print(f"LQ questions: {len(classification)}")
    print(f"  one topic:  {n_one}")
    print(f"  two topics: {n_two}")
    print(f"  fallback:   {n_fallback}")
    print(f"  placements: {placements}")


if __name__ == "__main__":
    main()
